//
//  HelloInteractor.swift
//  DemoCleanSwift
//
//  Created by Talish George on 25/3/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelloBusinessLogic
{
  func doSomething(request: Hello.Something.Request)
}

protocol HelloDataStore
{
  //var name: String { get set }
}

class HelloInteractor: HelloBusinessLogic, HelloDataStore
{
  var presenter: HelloPresentationLogic?
  var worker: HelloWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Hello.Something.Request)
  {
    worker = HelloWorker()
    worker?.doSomeWork()
    
    let response = Hello.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
